---
title: "Pilot analysis PAL"
author: "Irene Sophia Plank"
date: "2023-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(ggplot2)         # plots
library(ggstatsplot)     # ggplot with stats
library(pastecs)
library(ggrain)
library(cowplot)
library(readr)

source("R_rainclouds.R")
source("summarySE.R")

fl.path = paste('/home/iplank/Documents/EMBA', 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = fl.path)

```

## R Markdown

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# Behavioural data

```{r load_data, warning=F, message=F}
# load the relevant data in long format
df.tsk = list.files(path = fl.path, pattern = "PAL-BV_*", full.names = T) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "ccddddccddcd")) %>% 
  mutate(
    key = as.numeric(key)
  ) %>% 
  mutate(emotion = as.factor(emotion),
         choice = case_when(
                key == 6 & key_pos == "right" ~ "positive",
                key == 4 & key_pos == "right" ~ "negative",
                key == 6 & key_pos == "left"  ~ "negative",
                key == 4 & key_pos == "left"  ~ "positive",
                ),
         acc = emotion == choice,
         noise = as.factor(noise),
         noise = recode_factor(noise,
                "2" = "high",
                "3" = "low",
                "4" = "none"),
         expected = as.factor(ut),
         expected = recode_factor(expected,
                "0" = "unexpected",
                "1" = "expected"),
         rtc = case_when(acc == T ~ rt)) %>%
  select(subID, ut, noise, rt, rtc, acc, expected)

```

```{r plot_data, warning=F, message=F}

df.tsk_agg = df.tsk %>%
  group_by(subID, expected) %>%
  summarise(
    rt_agg = mean(rtc, na.rm = T),
    acc    = sum(acc == TRUE),
    rt_all = mean(rt, na.rm = T)
  ) %>% ungroup() %>%
  filter(rt_agg != "NaN")

df.diff = df.tsk_agg %>%
  select(subID, expected, rt_agg) %>%
  pivot_wider(names_from = "expected", values_from = rt_agg) %>%
  group_by(subID) %>%
  mutate(
    rt_diff = unexpected - expected
  )
  
write_csv(stat.desc(df.diff) %>% add_rownames(var = "stats"), "PAL_difference.csv")

write_csv(stat.desc(df.tsk_agg %>% filter(expected == "expected") %>% select(acc, rt_agg, rt_all)) %>% add_rownames(var = "stats"), "PAL_expected.csv")
write_csv(stat.desc(df.tsk_agg %>% filter(expected == "unexpected") %>% select(acc, rt_agg, rt_all)) %>% add_rownames(var = "stats"), "PAL_unexpected.csv")

nrow(df.tsk_agg)/2

ggwithinstats(data = df.tsk_agg,
              x    = expected, 
              y    = rt_agg, 
              ylab = "reaction time", xlab = "")


# ggplot(df.tsk_agg, aes(x = expected, y = rt_agg, fill =  expected)) +
#     geom_rain(rain.side = 'f')
# 
# df.tsk_sum <- summarySE(df.tsk_agg, measurevar = "rt_agg", groupvars="expected")
# 
# ggplot(df.tsk_agg, aes(x = expected, y = rt_agg, fill = expected)) +
#   geom_flat_violin(aes(fill = expected), position = position_nudge(x = .1, y = 0), adjust = 1.5, trim = FALSE, alpha = .5, colour = NA)+
#   geom_point(aes(x = as.numeric(expected)-.15, y = rt_agg, colour = expected),position = position_jitter(width = .05), size = .25, shape = 20)+
#   geom_boxplot(aes(x = expected, y = rt_agg, fill = expected),outlier.shape = NA, alpha = .5, width = .1, colour = "black") +
#   geom_line(data = df.tsk_sum, aes(x = as.numeric(expected)+.1, y = rt_agg_mean, group = expected, colour = expected), linetype = 3)+
#   geom_point(data = df.tsk_sum, aes(x = as.numeric(expected)+.1, y = rt_agg_mean, group = expected, colour = expected), shape = 18) +
#   geom_errorbar(data = df.tsk_sum, aes(x = as.numeric(expected)+.1, y = rt_agg_mean, group = expected, colour = expected, ymin = rt_agg_mean-sem, ymax = rt_agg_mean+sem), width = .05)+
#   scale_colour_brewer(palette = "Dark2")+
#   scale_fill_brewer(palette = "Dark2")+
#   ggtitle("Figure R11: Repeated Measures - Factorial (Extended)")

```

# Eye tracking data

```{r load_et, warning=F, message=F, include=F}

# load the relevant data in long format
df.eye = list.files(path = fl.path, pattern = "PAL-ET-*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(.x, show_col_types = F, col_types = cols(Comment = "c")), .id = "filename") %>% 
  mutate(
    subID = substr(filename, nchar(filename)-27, nchar(filename)-18)
    ) %>% 
  select(-filename) %>%
  separate(Comment, c("type", "trial", "ut", "noise", "iti", "tone", "emo"), 
           convert = T, extra = "merge", sep = "_") %>%
  relocate(subID, type, trial, ut, noise, iti, tone, emo)

# adding NA rows to have equal rows per subject
maxgp = max(table(df.eye$subID)) + 500
df.eye = df.eye %>%
  group_by(subID) %>%
  summarise(
    across(
      everything(),
      ~c(.x, rep(NA, maxgp-n()))
    )
  )

# add a trial sample count for trial-based analysis
df.eye$t = NA
idx = which(df.eye$type == "pic")
srs = 500      # sample rate per second
max = 1500      # how many ms in total
t = seq(0,max-1,2)
for (i in idx) {
  df.eye$t[i:(i+length(t)-1)] = t
}

# figure out blinks and set relevant columns to NA when there is a blink
df.eye_sel = df.eye %>%
  filter(!is.na(t)) %>%
  mutate(
    # find blinks
    blink = case_when(
      LeftScreenX == 0 & LeftScreenY == 0 & RightScreenX == 0 & RightScreenY == 0 & 
        LeftPupilMajorAxis == 0 & LeftPupilMinorAxis == 0 & RightPupilMajorAxis == 0 & RightPupilMinorAxis == 0 ~ 1,
      T ~ 0
    ),
    # set important values to NAs when blinks occur
    LeftPupilMinorAxis  = case_when(blink == 0 ~ LeftPupilMinorAxis),
    LeftPupilMajorAxis = case_when(blink == 0 ~ LeftPupilMajorAxis),
    RightPupilMinorAxis  = case_when(blink == 0 ~ RightPupilMinorAxis),
    RightPupilMajorAxis = case_when(blink == 0 ~ RightPupilMajorAxis),
    # calculate pupil size for both eyes separately
    LeftPupil = LeftPupilMajorAxis * LeftPupilMinorAxis * pi,
    RightPupil = RightPupilMajorAxis * RightPupilMinorAxis * pi,
    # recode some stuff
    noise = recode_factor(as.factor(noise),
            "2" = "high",
            "3" = "low",
            "4" = "none"),
    expected = recode_factor(as.factor(ut),
            "0" = "unexpected",
            "1" = "expected")
  ) %>%
  group_by(subID) %>%
  fill(type, trial, expected, noise, emo) %>%
  # calculate row wise mean based on both pupils
  rowwise() %>%
  mutate(
    PupilSize = mean(c(LeftPupil, RightPupil), na.rm = T)
  ) %>%
  select(type, trial, expected, noise, emo, t, PupilSize)

# BASELINE CORRECTION IS MISSING

# aggregate trials per condition and subject
df.eye_agg = df.eye_sel %>%
  group_by(subID, expected, t) %>%
  summarise(
    PupilSize  = mean(PupilSize, na.rm = T)
  )

df.eye_agg = merge(df.eye_agg, df.tsk_agg)

# plot this for each participant separately
ggplot(data = df.eye_agg, aes(x = t, y = PupilSize, colour = expected)) +
  geom_line() +
  #geom_vline(xintercept = 200) +
  #geom_vline(aes(xintercept = mean(rt_agg+200))) +
  facet_wrap(. ~ subID, nrow = 5, ncol = 3) +
  theme_bw() 

```