---
title: "Check BV and ET for all tasks"
author: "Irene Sophia Plank"
date: "2023-01-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(kableExtra)      # kbl

fl.path = '/home/iplank/Documents/EMOPRED'
dt.path = paste(fl.path, 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = fl.path)

```

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

# FAB task
```{r fab, warning=F, message=F}

# FAB ---------------------------------------------------------------------

# check whether responses are always the same
df.fab = list.files(path = dt.path, pattern = "FAB-BV_*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cddddddddcd"), .id = "fln") %>% 
  mutate(
    key = as.numeric(key), 
    subID = substr(fln, nchar(fln)-27, nchar(fln)-18),
    subID = recode(subID, "NRLOGZLVV4" = "FNRLOGZLVV")
  ) %>%
  group_by(subID, fln) %>%
  summarise(
    trls.fab = n(),
    rsps.fab = n_distinct(key)
  ) %>%
  select(-fln)

# check number of trials for eye tracking
df.fab_eye = list.files(path = dt.path, pattern = "FAB-ET-*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(.x, show_col_types = F, col_types = cols(Comment = "c")), .id = "filename") %>% 
  mutate(
    subID = substr(filename, nchar(filename)-27, nchar(filename)-18)
  ) %>% 
  select(-filename) %>%
  separate(Comment, c("type", "trial", "left", "right", "target", "congruent"), convert = T) %>%
  select(subID, type, trial) %>%
  filter(type == "tar") %>%
  group_by(subID) %>%
  summarise(
    trls_eye.fab = n()
  )

# merge together
df.fab = merge(df.fab, df.fab_eye, all = T)

# who is missing either eye tracking or behavioural data?
df.fab %>% filter(if_any(everything(), is.na))

# who is missing trials or has weird responses?
df.fab %>% filter(trls.fab != 432 | rsps.fab != 2 | trls_eye.fab != 432 | trls.fab != trls_eye.fab)

# how many full datasets do we have?
nrow(df.fab %>% filter(trls.fab == 432 & rsps.fab > 1 & trls.fab == trls_eye.fab))

```
# FER task
```{r fer, warning=F, message=F}
# FER ---------------------------------------------------------------------

# check whether responses are always the same
df.fer = list.files(path = dt.path, pattern = "FER-BV_*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cdcdddc"), .id = "fln") %>% 
  mutate(
    lastkey = as.numeric(lastkey),
    subID = substr(fln, nchar(fln)-27, nchar(fln)-18)
  ) %>% 
  group_by(subID) %>%
  summarise(
    trls.fer = n(),
    rsps.fer = n_distinct(opt)
  )

# check number of trials for eye tracking
df.fer_eye = list.files(path = dt.path, pattern = "FER-ET-*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(.x, show_col_types = F, col_types = cols(Comment = "c")), .id = "filename") %>% 
  mutate(
    subID = substr(filename, nchar(filename)-27, nchar(filename)-18)
  ) %>% 
  select(-filename) %>% 
  separate(Comment, c("type", "trial", "morph", "stm")) %>%
  filter(morph == "1") %>%
  group_by(subID) %>%
  summarise(
    trls_eye.fer = n()
  )

# merge together
df.fer = merge(df.fer, df.fer_eye, all = T)

# who is missing either eye tracking or behavioural data?
df.fer %>% filter(if_any(everything(), is.na))

# who is missing trials or has weird responses?
df.fer %>% filter(trls.fer != 64 | rsps.fer != 4 | trls_eye.fer != 64 | trls.fer != trls_eye.fer)

# how many full datasets do we have?
nrow(df.fer %>% filter(trls.fer == 64 & rsps.fer == 4 & trls.fer == trls_eye.fer))

```
# CTR task
```{r ctr, warning=F, message=F}
# CTR ---------------------------------------------------------------------

# check whether responses are always the same
df.ctr = list.files(path = dt.path, pattern = "CTR-BV_*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cdcdddc"), .id = "fln") %>% 
  mutate(
    lastkey = as.numeric(lastkey),
    subID = substr(fln, nchar(fln)-27, nchar(fln)-18)
  ) %>% 
  group_by(subID) %>%
  summarise(
    trls.ctr = n(),
    rsps.ctr = n_distinct(opt)
  )

# check number of trials for eye tracking
df.ctr_eye = list.files(path = dt.path, pattern = "CTR-ET-*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(.x, show_col_types = F, col_types = cols(Comment = "c")), .id = "filename") %>% 
  mutate(
    subID = substr(filename, nchar(filename)-27, nchar(filename)-18)
  ) %>% 
  select(-filename) %>% 
  separate(Comment, c("type", "trial", "morph", "stm")) %>%
  filter(morph == "1") %>%
  group_by(subID) %>%
  summarise(
    trls_eye.ctr = n()
  )

# merge together
df.ctr = merge(df.ctr, df.ctr_eye, all = T)

# who is missing either eye tracking or behavioural data?
df.ctr %>% filter(if_any(everything(), is.na))

# who is missing trials or has weird responses?
df.ctr %>% filter(trls.ctr != 16 | rsps.ctr != 4 | trls_eye.ctr != 16 | trls.ctr != trls_eye.ctr)

# how many full datasets do we have?
nrow(df.ctr %>% filter(trls.ctr == 16 & rsps.ctr == 4 & trls.ctr == trls_eye.ctr))

```
# PAL task
```{r pal, warning=F, message=F}
# PAL ---------------------------------------------------------------------

# check whether responses are always the same
df.pal = list.files(path = dt.path, pattern = "PAL-BV_*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "ccddddccddcd"), .id = "fln") %>% 
  mutate(
    key = as.numeric(key),
    subID = substr(fln, nchar(fln)-27, nchar(fln)-18)
  ) %>% 
  group_by(subID) %>%
  summarise(
    trls.pal = n(),
    rsps.pal = n_distinct(key),
    nrsp.pal = sum(!is.na(key))
  )

# check number of trials for eye tracking
df.pal_eye = list.files(path = dt.path, pattern = "PAL-ET-*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(.x, show_col_types = F, col_types = cols(Comment = "c")), .id = "filename") %>% 
  mutate(
    subID = substr(filename, nchar(filename)-27, nchar(filename)-18)
  ) %>% 
  select(-filename) %>%
  separate(Comment, c("type", "trial", "ut", "noise", "iti", "tone", "emo"), 
           convert = T, extra = "merge", sep = "_") %>%
  filter(type == "pic") %>%
  group_by(subID) %>%
  summarise(
    trls_eye.pal = n()
  )

# merge together
df.pal = merge(df.pal, df.pal_eye, all = T)

# who is missing either eye tracking or behavioural data?
df.pal %>% filter(if_any(everything(), is.na))

# who is missing trials or has weird responses?
df.pal %>% filter(trls.pal != 336 | rsps.pal <= 1 | trls_eye.pal != 336 | trls.pal != trls_eye.pal | nrsp.pal < 336)

# how many full datasets do we have?
nrow(df.pal %>% filter(trls.pal == 336 & rsps.pal > 1 & trls.pal == trls_eye.pal))

```
# VMM task
```{r vmm, warning=F, message=F}
# VMM ---------------------------------------------------------------------

# check number of trials
df.vmm = list.files(path = dt.path, pattern = "*.tsv$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, delim = "\t"), .id = "Filename") %>% 
  select(-Filename) %>%
  filter(`type(str)` == "pic") %>%
  rename("subID" = "Subject") %>%
  group_by(subID) %>%
  summarise(
    trls.vmm = n()
  ) %>%
  mutate(
    runs.vmm = if_else(trls.vmm > 1190,2,1)
  )

# check number of trials for eye tracking
df.vmm_eye = list.files(path = dt.path, pattern = "*\\.msg$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, col_names = F, delim = "\t"), .id = "Filename") %>%
  mutate(
    subID = sub(paste(dt.path,"/",sep = ""), "", Filename),
    subID = substr(subID,1,10)
  ) %>%
  separate(X2, into = c("frame", "trial", "trlno")) %>%
  select(-Filename) %>%
  filter(trial == "TRIALID") %>%
  group_by(subID) %>%
  summarise(
    trls_eye.vmm = n()
  )

# get design number
df.vmm_des = list.files(path = dt.path, pattern = "*.tsv$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, delim = "\t"), .id = "Filename") %>% 
  select(-Filename) %>%
  filter(`type(str)` == "pic") %>%
  rename("subID" = "Subject", "run" = "run(num)") %>%
  select(subID, run) %>% distinct() %>%
  group_by(subID) %>%
  summarise(
    ord = paste(run, collapse = "_")
  )

df.des = list.files(path = paste(dt.path,"Designs",sep = "/"), pattern = "*.txt$", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_delim(., show_col_types = F, delim = "\t", col_names = F), .id = "Filename") %>%
  mutate(
    des = gsub("\\D+", "", Filename),
    des = substr(des, 1, nchar(des)-1)
  ) %>%
  select(des, X10) %>% distinct() %>% 
  group_by(des) %>%
  summarise(
    ord = paste(X10, collapse = "_")
  ) %>% 
  group_by(ord) %>%
  summarise(
    des = paste(des, collapse = "_")
  )
  
df.des = merge(df.vmm_des, df.des, all.x = T)

# merge together
df.vmm = merge(df.vmm, df.vmm_eye, all = T)

# who is missing either eye tracking or behavioural data?
df.vmm %>% filter(if_any(everything(), is.na))

# who is missing trials or has weird responses?
df.vmm %>% filter((trls.vmm != 1190 & runs.vmm == 1) | (trls.vmm != 2380 & runs.vmm == 2) | trls.vmm != trls_eye.vmm)

# how many full datasets do we have?
nrow(df.vmm %>% filter(((trls.vmm == 1190 & runs.vmm == 1) | (trls.vmm == 2380 & runs.vmm == 2)) & trls.vmm == trls_eye.vmm & !is.na(trls_eye.vmm)))

```

# All tasks
```{r all, warning=F, message=F}

# join all the data
df.ls = list(df.fab, df.fer, df.ctr, df.pal, df.vmm)
df = df.ls %>% reduce(full_join, by = "subID")

# show it
kbl(df) %>% kable_styling(bootstrap_options = c("striped", "hover", "responsive"))

```