---
title: "Analysis FAB: Behavioural Data"
author: "Irene Sophia Plank"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)           # kable
library(tidyverse)       # tibble stuff
library(ggplot2)         # plots
library(ggstatsplot)     # ggplot with stats
library(ggrain)          # rainplots

fl.path = '/home/emba/Documents/EMBA'
dt.path = paste(fl.path, 'BVET', sep = "/")
knitr::opts_knit$set(root.dir = fl.path)

```

## R Markdown

<style type="text/css">
.main-container {
  max-width: 1100px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r load_data, warning=F, message=F}
# load the relevant data in long format
df.tsk = list.files(path = dt.path, pattern = "FAB-BV_*", full.names = T) %>%
  setNames(nm = .) %>%
  map_df(~read_csv(., show_col_types = F, col_types = "cddddddddcd"), .id = "fln") %>% 
  mutate(subID = substr(fln, nchar(fln)-27, nchar(fln)-18),
         target = as.factor(target),
         target = recode(target, 
                "1" = "left",
                "2" = "right"),
         # sometimes participants used wrong row or caps was on
         choice = recode(key,
                "4" = "left",
                "LeftArrow" = "left", 
                "1" = "left", 
                "RightArrow" = "right", 
                "6" = "right", 
                "+" = "right"),
         acc = target == choice,
         cue = as.factor(congruent),
         cue = recode_factor(cue,
                "1" = "face",
                "0" = "object"),
         stm = if_else(left < right, paste(left, right, sep = "_"), paste(right, left, sep = "_"))) %>%
  select(subID, trl, stm, rt, acc, cue, target) %>%
  filter(nchar(subID) == 10) %>% 
  # outlier detection with IQR method
  group_by(subID) %>%
  mutate(rt.up = quantile(rt, 0.75) + 1.5 * IQR(rt),
         rt.lo = quantile(rt, 0.25) - 1.5 * IQR(rt),
         rt    = case_when(rt > rt.lo & rt < rt.up ~ rt),
         use   = case_when(!is.na(rt) & acc & rt > rt.lo & rt < rt.up ~ T,
                           T ~ F),
         rt.cor = if_else(acc, rt, NA)
         )

df.tsk_acc = df.tsk %>%
  group_by(subID) %>%
  summarise(
    acc = mean(use)
  )

# does anyone have to be excluded?
exc = df.tsk_acc %>% filter(acc < 2/3)
exc = as.character(exc$subID)
print(length(exc)) # print how many have to be excluded

# load pilot participants and add to the list. This also includes one participant who had to be excluded due receiving an additional diagnosis, therefore, being diagnosed with both ADHD and ASD
pilot = read_csv(paste0(dt.path, "/pilot-subIDs.csv"))
exc   = c(exc, pilot$subID)

# exclude these participants
df.tsk = df.tsk %>% filter(!(subID %in% exc))

# sample size
nrow(df.tsk) / 432

# save data frame
saveRDS(df.tsk, paste0(dt.path, "/df_FAB.RDS"))

```

```{r plot_data, warning = F, message = F}

df.tsk_agg = df.tsk %>% filter(acc == TRUE) %>%
  group_by(subID, cue) %>%
  summarise(
    rt.agg = mean(rt, na.rm = T)
  )

nrow(df.tsk_agg)/2

ggwithinstats(data = df.tsk_agg, 
              x    = cue, 
              y    = rt.agg)

```
